import random

# ==============================================================================
# PUZZLE BANK (150 QUESTIONS - FULLY ANNOTATED)
# ==============================================================================
# Each puzzle now contains 'chakra' and 'ethical_category' keys.
# - Chakra: Relates to the energy center the question's theme activates.
# - Ethical Focus: Relates to the core moral concept being tested.
# ==============================================================================

PUZZLES = {
    "ethics_philosophy": [
        # Basic (10)
        {"id": "eth_b_1", "question": "What is the concept of 'Karma'?", "answer": "The sum of a person's actions and their consequences", "options": ["A type of meditation", "A religious festival", "The sum of a person's actions and their consequences", "A sacred text"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Cause and Effect", "analysis": {"principle": "Cause and Effect", "implication": "Every action, good or bad, will eventually return to the person."}},
        {"id": "eth_b_2", "question": "What does the term 'Dharma' broadly mean?", "answer": "Righteous conduct and one's duty", "options": ["Wealth and prosperity", "Righteous conduct and one's duty", "Liberation from rebirth", "A magical chant"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Duty", "analysis": {"principle": "Righteousness", "implication": "Following one's Dharma is key to a balanced and ethical life."}},
        {"id": "eth_b_3", "question": "The ethical principle of 'Ahimsa' refers to what?", "answer": "Non-violence", "options": ["Truthfulness", "Non-stealing", "Non-violence", "Charity"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Compassion", "implication": "Ahimsa extends to all living beings in thought, word, and deed."}},
        {"id": "eth_b_4", "question": "What is the opposite of Dharma?", "answer": "Adharma", "options": ["Karma", "Moksha", "Adharma", "Artha"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Duality", "implication": "Recognizing Adharma (unrighteousness) is the first step to choosing Dharma."}},
        {"id": "eth_b_5", "question": "The concept of 'Satya' is the principle of...?", "answer": "Truthfulness", "options": ["Truthfulness", "Purity", "Contentment", "Self-study"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Throat", "ethical_category": "Honesty", "analysis": {"principle": "Integrity", "implication": "Satya means being truthful in thought, speech, and action."}},
        {"id": "eth_b_6", "question": "In philosophy, what is a 'moral dilemma'?", "answer": "A conflict between two or more moral principles", "options": ["A solved ethical problem", "A conflict between two or more moral principles", "A popular opinion", "A law of physics"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Discernment", "implication": "Life often presents situations where choosing the 'right' path is complex."}},
        {"id": "eth_b_7", "question": "The act of 'Seva' in Indian culture refers to what?", "answer": "Selfless service", "options": ["Daily prayer", "A form of dance", "Selfless service", "A pilgrimage"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Selflessness", "implication": "Performing Seva without expectation of reward purifies the heart."}},
        {"id": "eth_b_8", "question": "What is the 'Golden Rule' found in many cultures?", "answer": "Treat others as you want to be treated", "options": ["The winner takes all", "Might makes right", "Treat others as you want to be treated", "The early bird gets the worm"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Empathy", "implication": "This universal principle fosters compassion and mutual respect."}},
        {"id": "eth_b_9", "question": "The principle of 'Asteya' means what?", "answer": "Non-stealing", "options": ["Non-possessiveness", "Non-stealing", "Cleanliness", "Moderation"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Honesty", "analysis": {"principle": "Honesty", "implication": "Asteya includes not just physical objects, but also ideas and opportunities."}},
        {"id": "eth_b_10", "question": "Why is 'gratitude' considered a virtue?", "answer": "It promotes contentment and positive relationships", "options": ["It makes one wealthy", "It is a sign of weakness", "It promotes contentment and positive relationships", "It is required by law"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Balance", "analysis": {"principle": "Contentment", "implication": "Being grateful for what one has reduces envy and increases happiness."}},
        {"id": "eth_i_1", "question": "What are the four 'Purusharthas' or aims of human life?", "answer": "Dharma, Artha, Kama, Moksha", "options": ["Brahmin, Kshatriya, Vaishya, Shudra", "Dharma, Artha, Kama, Moksha", "Rig, Sama, Yajur, Atharva", "Childhood, Youth, Adult, Old Age"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Crown", "ethical_category": "Purpose", "analysis": {"principle": "Life's Purpose", "implication": "A balanced life addresses duty, prosperity, desire, and the ultimate goal of liberation."}},
        {"id": "eth_i_2", "question": "The philosophical school of 'Advaita Vedanta' primarily teaches what?", "answer": "The non-dualistic nature of the self (Atman) and reality (Brahman)", "options": ["The existence of many gods", "The non-dualistic nature of the self (Atman) and reality (Brahman)", "Atheism", "The worship of nature"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Crown", "ethical_category": "Wisdom", "analysis": {"principle": "Oneness", "implication": "It posits that the individual soul is not different from the ultimate reality."}},
        {"id": "eth_i_3", "question": "What is the difference between 'Shreyas' and 'Preyas' in Kathopanishad?", "answer": "'Shreyas' is the good/righteous path, 'Preyas' is the pleasant/pleasurable path", "options": ["Shreyas is wealth, Preyas is health", "'Shreyas' is the good/righteous path, 'Preyas' is the pleasant/pleasurable path", "They are two names for the same concept", "Shreyas is for kings, Preyas is for commoners"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Wise Choice", "implication": "The wise choose the path of long-term good over short-term pleasure."}},
        {"id": "eth_i_4", "question": "The concept of the 'Gunas' (Sattva, Rajas, Tamas) relates to what?", "answer": "The three fundamental qualities or modes of nature", "options": ["The stages of life", "The types of rituals", "The three fundamental qualities or modes of nature", "The primary epic poems"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Inherent Qualities", "implication": "Understanding the Gunas helps in understanding one's own nature and the world."}},
        {"id": "eth_i_5", "question": "What does 'Nishkama Karma', as taught in the Bhagavad Gita, mean?", "answer": "Performing actions without attachment to the results", "options": ["Ceasing all action", "Performing actions only for personal gain", "Performing actions without attachment to the results", "Actions performed in secret"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Duty", "analysis": {"principle": "Detached Action", "implication": "This is the path of the Karma Yogi, focusing on duty rather than reward."}},
        {"id": "eth_i_6", "question": "The Yamas and Niyamas in Yoga philosophy are what?", "answer": "Ethical rules and personal observances", "options": ["Breathing exercises", "Physical postures", "Ethical rules and personal observances", "Types of meditation"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Discipline", "analysis": {"principle": "Foundation of Yoga", "implication": "They form the ethical foundation upon which the practice of Yoga is built."}},
        {"id": "eth_i_7", "question": "The principle of 'Aparigraha' means what?", "answer": "Non-possessiveness or non-hoarding", "options": ["Non-violence", "Truthfulness", "Non-possessiveness or non-hoarding", "Self-discipline"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Balance", "analysis": {"principle": "Minimalism", "implication": "It encourages taking only what is necessary and letting go of greed."}},
        {"id": "eth_i_8", "question": "What is 'Svadhyaya'?", "answer": "Self-study and study of scriptures", "options": ["Charity", "Self-study and study of scriptures", "Fasting", "Silence"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Introspection", "implication": "It is the path to self-knowledge and understanding the nature of reality."}},
        {"id": "eth_i_9", "question": "The virtue of 'Kshama' refers to what?", "answer": "Forgiveness", "options": ["Courage", "Patience", "Forgiveness", "Humility"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Letting Go", "implication": "Kshama is considered a great strength, freeing oneself from the burden of resentment."}},
        {"id": "eth_i_10", "question": "How is 'Maya' generally understood in Hindu philosophy?", "answer": "The illusory power that makes the universe appear as real", "options": ["A benevolent mother goddess", "The ultimate reality", "The illusory power that makes the universe appear as real", "A state of perfect happiness"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Illusion vs. Reality", "implication": "Spiritual practice aims to see beyond Maya to the true nature of reality (Brahman)."}},
        {"id": "eth_a_1", "question": "What is 'Apad Dharma'?", "answer": "The prescribed conduct during times of extreme adversity or emergency", "options": ["The dharma of kings", "The dharma of a student", "The prescribed conduct during times of extreme adversity or emergency", "The final stage of life"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Root", "ethical_category": "Duty", "analysis": {"principle": "Contextual Ethics", "implication": "It acknowledges that in desperate situations, actions normally considered Adharma may be permissible."}},
        {"id": "eth_a_2", "question": "In the concept of 'Rina' (debt), what is 'Pitri Rina'?", "answer": "The debt to one's ancestors", "options": ["Debt to the gods", "Debt to the sages", "The debt to one's ancestors", "Financial debt"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Root", "ethical_category": "Duty", "analysis": {"principle": "Obligation", "implication": "This debt is traditionally repaid by having righteous children and upholding family traditions."}},
        {"id": "eth_a_3", "question": "What is the key difference between the philosophical schools of Dvaita and Advaita?", "answer": "Dvaita posits a dualistic reality (God and soul are separate), while Advaita posits non-dualism", "options": ["Dvaita is older than Advaita", "Dvaita posits a dualistic reality (God and soul are separate), while Advaita posits non-dualism", "Advaita has more gods", "Dvaita rejects the Vedas"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Wisdom", "analysis": {"principle": "Metaphysical Views", "implication": "These schools offer different interpretations on the relationship between the individual and the divine."}},
        {"id": "eth_a_4", "question": "The 'Cārvāka' school of philosophy is known for what belief?", "answer": "Materialism and skepticism of religious claims", "options": ["Atheism", "Devotion to a single god", "Materialism and skepticism of religious claims", "The belief in reincarnation"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Empiricism", "implication": "Cārvāka was a heterodox school that accepted only direct perception as a means of knowledge."}},
        {"id": "eth_a_5", "question": "What is the 'Neti, Neti' (not this, not that) method of philosophical analysis?", "answer": "A way of understanding reality by negating all descriptions of it", "options": ["A debating technique", "A way of understanding reality by negating all descriptions of it", "A ritual chant", "A memory technique"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Via Negativa", "implication": "It is used to describe the indescribable Brahman by eliminating what it is not."}},
        {"id": "eth_a_6", "question": "How does the concept of 'Jivanmukti' differ from 'Videhamukti'?", "answer": "Jivanmukti is liberation while still alive, Videhamukti is liberation after death", "options": ["Jivanmukti is for men, Videhamukti is for women", "Jivanmukti is liberation while still alive, Videhamukti is liberation after death", "They are identical", "Jivanmukti is partial liberation, Videhamukti is full liberation"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Purpose", "analysis": {"principle": "States of Liberation", "implication": "This highlights the possibility of achieving an enlightened state while living in the world."}},
        {"id": "eth_a_7", "question": "What is the 'Sthitaprajna' as described in the Bhagavad Gita?", "answer": "A person of steady wisdom, unperturbed by dualities like pleasure and pain", "options": ["A great warrior", "A person of steady wisdom, unperturbed by dualities like pleasure and pain", "A wealthy merchant", "A king who has renounced his throne"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Balance", "analysis": {"principle": "Equanimity", "implication": "This is the ideal state of a self-realized individual."}},
        {"id": "eth_a_8", "question": "The 'Pancha Mahayajnas' (five great sacrifices) are duties towards whom?", "answer": "Gods, Sages, Ancestors, Fellow Humans, and other Living Beings", "options": ["One's King, Teacher, and Parents", "The five elements", "Gods, Sages, Ancestors, Fellow Humans, and other Living Beings", "One's own body and mind"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Heart", "ethical_category": "Duty", "analysis": {"principle": "Cosmic Duty", "implication": "These daily duties for a householder maintain harmony in the cosmic and social order."}},
        {"id": "eth_a_9", "question": "In Jain philosophy, what is the concept of 'Anekantavada'?", "answer": "The principle of many-sidedness or non-absolutism", "options": ["Extreme asceticism", "The principle of many-sidedness or non-absolutism", "The belief in a creator god", "The path of non-violence"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Relative Truth", "implication": "It teaches that ultimate truth and reality are complex and have multiple aspects."}},
        {"id": "eth_a_10", "question": "What is the primary ethical conflict for Arjuna in the Bhagavad Gita?", "answer": "His duty as a warrior (Kshatriya Dharma) versus his personal compassion for his family", "options": ["His desire for power versus his fear of losing", "His duty as a warrior (Kshatriya Dharma) versus his personal compassion for his family", "A choice between two kingdoms", "A disagreement over the rules of war"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Heart", "ethical_category": "Duty", "analysis": {"principle": "Conflict of Duties", "implication": "This dilemma serves as the foundation for Krishna's teachings on Dharma and detached action."}},
    ],
    "mathematics": [
        {"id": "math_b_1", "question": "If a square has a side length of 12 cm, what is its perimeter?", "answer": "48 cm", "options": ["24 cm", "144 cm", "36 cm", "48 cm"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Order", "analysis": {"principle": "Boundaries", "implication": "Understanding perimeters relates to defining limits and structures."}},
        {"id": "math_b_2", "question": "What is 50% of 250?", "answer": "125", "options": ["100", "125", "150", "50"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Proportion", "implication": "Grasping percentages is key to understanding proportions in the world."}},
        {"id": "math_b_3", "question": "Solve for x: x - 15 = 30", "answer": "45", "options": ["15", "30", "45", "60"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Balance", "implication": "Algebra teaches that balance must be maintained to find the truth."}},
        {"id": "math_b_4", "question": "What is the sum of the angles in a triangle?", "answer": "180 degrees", "options": ["90 degrees", "180 degrees", "360 degrees", "100 degrees"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Order", "analysis": {"principle": "Harmony", "implication": "The fixed sum of angles shows an inherent order and harmony in geometry."}},
        {"id": "math_b_5", "question": "If a train travels at 60 km/h, how far will it travel in 3 hours?", "answer": "180 km", "options": ["120 km", "63 km", "20 km", "180 km"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Cause and Effect", "analysis": {"principle": "Causality", "implication": "This demonstrates a direct relationship between time, speed, and outcome."}},
        {"id": "math_b_6", "question": "What is the next number in the sequence: 2, 4, 6, 8, ...?", "answer": "10", "options": ["12", "10", "9", "16"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Pattern Recognition", "implication": "Recognizing patterns is fundamental to understanding cosmic and life cycles."}},
        {"id": "math_b_7", "question": "How many sides does a hexagon have?", "answer": "6", "options": ["5", "8", "6", "7"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Order", "analysis": {"principle": "Structure", "implication": "Geometric shapes represent the underlying structure of the universe."}},
        {"id": "math_b_8", "question": "What is 15 multiplied by 10?", "answer": "150", "options": ["25", "150", "1500", "1.5"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Growth", "implication": "Multiplication shows how actions can have magnified consequences."}},
        {"id": "math_b_9", "question": "What is the area of a rectangle with length 10 and width 5?", "answer": "50", "options": ["30", "15", "50", "100"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Order", "analysis": {"principle": "Space", "implication": "Calculating area is understanding the space occupied by a defined form."}},
        {"id": "math_b_10", "question": "If you have 5 apples and you get 7 more, how many do you have?", "answer": "12", "options": ["10", "11", "12", "13"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Logic", "analysis": {"principle": "Accumulation", "implication": "Simple addition mirrors the accumulation of karma over time."}},
        {"id": "math_i_1", "question": "A shop offers a 20% discount on an item priced at ₹500. What is the final price?", "answer": "₹400", "options": ["₹480", "₹450", "₹400", "₹100"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Value", "implication": "Understanding discounts relates to discerning true value versus perceived value."}},
        {"id": "math_i_2", "question": "If 3x + 7 = 22, what is the value of x?", "answer": "5", "options": ["3", "5", "7", "9"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Uncovering Truth", "implication": "Solving for a variable is like a spiritual quest to find the unknown truth."}},
        {"id": "math_i_3", "question": "What is the area of a circle with a radius of 7 units? (Use π ≈ 22/7)", "answer": "154 sq units", "options": ["44 sq units", "154 sq units", "49 sq units", "88 sq units"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Order", "analysis": {"principle": "Wholeness", "implication": "The circle represents unity, infinity, and wholeness in many traditions."}},
        {"id": "math_i_4", "question": "The ratio of boys to girls in a class is 3:2. If there are 30 students in total, how many are boys?", "answer": "18", "options": ["12", "15", "18", "20"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Relationship", "implication": "Ratios help us understand the relationship and balance between different parts of a whole."}},
        {"id": "math_i_5", "question": "What is the value of 2 to the power of 5 (2^5)?", "answer": "32", "options": ["10", "16", "32", "64"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Exponential Growth", "implication": "This shows how small actions or seeds of karma can grow into massive consequences."}},
        {"id": "math_i_6", "question": "A person's salary increased from ₹10,000 to ₹12,000. What is the percentage increase?", "answer": "20%", "options": ["10%", "15%", "20%", "25%"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Change", "implication": "Calculating percentage change helps quantify the impermanent nature of worldly things."}},
        {"id": "math_i_7", "question": "Find the average of the numbers: 10, 20, 30, 40, 50.", "answer": "30", "options": ["25", "30", "35", "150"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Equilibrium", "implication": "Finding an average is like finding the central point or balance among different values."}},
        {"id": "math_i_8", "question": "If a car travels 300 km in 5 hours, what is its average speed?", "answer": "60 km/h", "options": ["50 km/h", "60 km/h", "70 km/h", "1500 km/h"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Pace of Life", "implication": "Understanding speed helps conceptualize the pace of one's journey through life."}},
        {"id": "math_i_9", "question": "What is the square root of 196?", "answer": "14", "options": ["13", "14", "15", "16"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Logic", "analysis": {"principle": "Finding the Root", "implication": "Finding a square root is like tracing an effect back to its original cause."}},
        {"id": "math_i_10", "question": "In a right-angled triangle, the two shorter sides are 5 cm and 12 cm. What is the length of the longest side (hypotenuse)?", "answer": "13 cm", "options": ["10 cm", "13 cm", "15 cm", "17 cm"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Order", "analysis": {"principle": "Pythagorean Harmony", "implication": "The theorem of Pythagoras reveals a hidden, perfect relationship between the sides of a right triangle."}},
        {"id": "math_a_1", "question": "A person invests ₹10,000 at 10% simple interest per year. How much interest will they earn in 3 years?", "answer": "₹3,000", "options": ["₹1,000", "₹3,000", "₹13,000", "₹3,310"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Accumulation over Time", "implication": "Simple interest is like linear karma, accumulating steadily through consistent action."}},
        {"id": "math_a_2", "question": "If an item is sold for ₹660 at a profit of 10%, what was its cost price?", "answer": "₹600", "options": ["₹600", "₹594", "₹726", "₹650"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Original Value", "implication": "This requires working backward to find the true source or cost, similar to introspection."}},
        {"id": "math_a_3", "question": "Two pipes can fill a tank in 10 and 15 hours respectively. If both are opened together, how long will it take to fill the tank?", "answer": "6 hours", "options": ["5 hours", "6 hours", "12.5 hours", "25 hours"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Synergy", "implication": "This demonstrates how combined efforts (actions) can lead to a faster outcome."}},
        {"id": "math_a_4", "question": "How many ways can 4 people be arranged in a line?", "answer": "24", "options": ["16", "20", "24", "256"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Order", "analysis": {"principle": "Permutations", "implication": "This illustrates the vast number of possibilities and outcomes that can arise from a few elements."}},
        {"id": "math_a_5", "question": "The sum of two numbers is 25 and their difference is 5. What are the numbers?", "answer": "15 and 10", "options": ["20 and 5", "15 and 10", "18 and 7", "12 and 13"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Simultaneous Truths", "implication": "This requires solving a system where two conditions must be true at once, mirroring complex ethical choices."}},
        {"id": "math_a_6", "question": "A man rows upstream at 8 km/h and downstream at 12 km/h. What is the speed of the stream?", "answer": "2 km/h", "options": ["4 km/h", "10 km/h", "2 km/h", "1 km/h"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Opposing Forces", "implication": "This represents the struggle between one's own efforts and the external forces of the world (like karma)."}},
        {"id": "math_a_7", "question": "What is the probability of drawing a king from a standard deck of 52 cards?", "answer": "1/13", "options": ["1/52", "4/13", "1/4", "1/13"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Logic", "analysis": {"principle": "Chance and Destiny", "implication": "Probability helps us understand the likelihood of events in a universe of countless possibilities."}},
        {"id": "math_a_8", "question": "A project can be completed by 10 men in 12 days. How many days will it take for 15 men to complete the same project?", "answer": "8 days", "options": ["18 days", "10 days", "8 days", "6 days"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Inverse Proportion", "implication": "This shows how increasing one factor (effort) can decrease another (time to result)."}},
        {"id": "math_a_9", "question": "A train 100 meters long is running at 36 km/h. How long will it take to cross an electric pole?", "answer": "10 seconds", "options": ["10 seconds", "12 seconds", "15 seconds", "20 seconds"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Logic", "analysis": {"principle": "Relative Perception", "implication": "This problem requires careful unit conversion, reminding us to see things from a consistent perspective."}},
        {"id": "math_a_10", "question": "What is the volume of a cube with a side length of 5 cm?", "answer": "125 cm³", "options": ["25 cm³", "100 cm³", "125 cm³", "150 cm³"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Root", "ethical_category": "Order", "analysis": {"principle": "Three-Dimensional Existence", "implication": "Volume represents the space one occupies, a metaphor for one's impact on the world."}},
    ],
    "cultural_knowledge": [
        # Basic (10) - Revised
        {"id": "cult_b_1_rev", "question": "You are invited to a friend's home for a meal. What is the most respectful first action upon entering?", "answer": "Remove your footwear", "options": ["Immediately ask for Wi-Fi", "Remove your footwear", "Start eating right away", "Compliment the TV"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Respect", "analysis": {"principle": "Purity of Space", "implication": "Removing shoes is a sign of respect for the sanctity and cleanliness of a home."}},
        {"id": "cult_b_2_rev", "question": "You meet an elder for the first time. What is the traditional gesture of greeting?", "answer": "Joining palms (Namaste) and a slight bow", "options": ["A firm handshake", "A high-five", "A simple 'hello'", "Joining palms (Namaste) and a slight bow"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Respect", "analysis": {"principle": "Recognizing Divinity", "implication": "'Namaste' signifies 'the divine in me bows to the divine in you,' showing deep respect."}},
        {"id": "cult_b_3_rev", "question": "Your friend is celebrating Diwali. What is a customary and appropriate gift to bring?", "answer": "A box of sweets (Mithai)", "options": ["A kitchen appliance", "A box of sweets (Mithai)", "A bouquet of white flowers", "Cash in an open envelope"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Generosity", "analysis": {"principle": "Sharing Joy", "implication": "Sweets represent the sharing of happiness and sweetness during festive occasions."}},
        {"id": "cult_b_4_rev", "question": "You are visiting a temple. What kind of attire is most appropriate?", "answer": "Modest clothing that covers shoulders and knees", "options": ["Beachwear", "Gym clothes", "Modest clothing that covers shoulders and knees", "Formal business suit"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Discipline", "analysis": {"principle": "Sanctity", "implication": "Dressing modestly shows reverence for the sacred space and the deities within."}},
        {"id": "cult_b_5_rev", "question": "An elder offers you 'prasad' (blessed food) from a temple. What is the correct way to receive it?", "answer": "With your right hand, supported by the left", "options": ["With your left hand only", "Ask for it to be packed", "With your right hand, supported by the left", "Refuse it politely"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Devotion", "analysis": {"principle": "Receiving Grace", "implication": "Using the right hand, considered pure, shows respect for the divine blessing being offered."}},
        {"id": "cult_b_6_rev", "question": "During a family dinner, who is generally expected to start eating first?", "answer": "The eldest person at the table", "options": ["The children", "The person who is hungriest", "The host", "The eldest person at the table"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Respect", "analysis": {"principle": "Hierarchy of Respect", "implication": "Allowing the eldest to start is a sign of deference and respect for their age and wisdom."}},
        {"id": "cult_b_7_rev", "question": "A street vendor gives you slightly extra change by mistake. What is the dharmic action?", "answer": "Inform them and return the extra amount", "options": ["Keep it as a lucky bonus", "Inform them and return the extra amount", "Give it to a beggar", "Assume it was a discount"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Throat", "ethical_category": "Honesty", "analysis": {"principle": "Satya (Truthfulness)", "implication": "Honesty in small matters builds a character that is truthful in large matters."}},
        {"id": "cult_b_8_rev", "question": "Your neighbor is playing loud music for a festival. What is the most community-minded approach?", "answer": "Tolerate it for a reasonable time as part of the celebration", "options": ["Immediately call the police", "Start playing your own music louder", "Tolerate it for a reasonable time as part of the celebration", "Confront them angrily"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Community Spirit", "implication": "Understanding and tolerance are key to harmonious living in a diverse community."}},
        {"id": "cult_b_9_rev", "question": "You see a cow wandering in the middle of a busy street. What is a common cultural reaction in India?", "answer": "Wait patiently or carefully navigate around it", "options": ["Honk loudly and continuously", "Wait patiently or carefully navigate around it", "Ignore it and expect others to handle it", "Try to scare it away"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Ahimsa (Non-violence)", "implication": "The reverence for cows leads to a patient and non-harming approach, even when inconvenient."}},
        {"id": "cult_b_10_rev", "question": "A friend invites you for 'Holi'. What should you expect and prepare for?", "answer": "To be playfully smeared with colored powders and water", "options": ["A quiet and formal gathering", "A black-tie dinner", "To be playfully smeared with colored powders and water", "A religious fast"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Sacral", "ethical_category": "Purity", "analysis": {"principle": "Joyful Participation", "implication": "Holi is about shedding inhibitions and celebrating the vibrancy of life and community."}},
        # Intermediate (10) - Revised
        {"id": "cult_i_1_rev", "question": "A foreign colleague asks why many Hindus are vegetarian. What is the most accurate primary reason to state?", "answer": "It is based on the principle of Ahimsa (non-violence) towards all beings", "options": ["It is cheaper than eating meat", "It is based on the principle of Ahimsa (non-violence) towards all beings", "All Indian food is naturally vegetarian", "It is a government regulation"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Ahimsa", "implication": "Explaining the core ethical principle behind the practice fosters better understanding."}},
        {"id": "cult_i_2_rev", "question": "You are invited to a traditional South Indian wedding. Which color might be considered inauspicious to wear as a guest?", "answer": "Black", "options": ["Red", "Gold", "Black", "Green"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Respect", "analysis": {"principle": "Cultural Symbolism", "implication": "While customs vary, black is often associated with mourning and is avoided at joyous occasions like weddings."}},
        {"id": "cult_i_3_rev", "question": "A senior colleague at work makes a significant mistake, but no one has noticed. What is the most ethical approach?", "answer": "Inform them of the mistake privately and discreetly", "options": ["Announce it in a team meeting to show your diligence", "Inform their boss directly", "Ignore it to avoid conflict", "Inform them of the mistake privately and discreetly"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Throat", "ethical_category": "Honesty", "analysis": {"principle": "Right Speech", "implication": "This approach balances truthfulness (Satya) with non-harm (Ahimsa), correcting the error without public humiliation."}},
        {"id": "cult_i_4_rev", "question": "Your friend's parents are visiting from their village. How should you address them to show respect?", "answer": "As 'Aunty' and 'Uncle'", "options": ["By their first names", "As 'Mr.' and 'Mrs.' [Last Name]", "As 'Aunty' and 'Uncle'", "Avoid addressing them directly"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Respect", "analysis": {"principle": "Familial Respect", "implication": "Using 'Aunty' and 'Uncle' is a common and warm way to show respect to elders, treating them as part of an extended family."}},
        {"id": "cult_i_5_rev", "question": "A person accidentally touches you with their foot. What is a common cultural response you might see from them?", "answer": "They will touch their hand to the spot and then to their heart or eyes as an apology", "options": ["They will ignore it completely", "They will laugh it off", "They will touch their hand to the spot and then to their heart or eyes as an apology", "They will offer to buy you a tea"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Respect", "analysis": {"principle": "Reverence for the Body", "implication": "Feet are considered unclean, so touching someone with them is disrespectful. The gesture is a sincere apology for this."}},
        {"id": "cult_i_6_rev", "question": "A friend asks about the concept of arranged marriage. What is a key point to explain its cultural context?", "answer": "It is traditionally seen as a union of two families, not just two individuals", "options": ["It is a way for parents to control their children", "It is done without the couple ever meeting", "It is traditionally seen as a union of two families, not just two individuals", "It is a purely financial transaction"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Duty", "analysis": {"principle": "Union of Families", "implication": "This perspective emphasizes community, stability, and shared values as the foundation of the marriage."}},
        {"id": "cult_i_7_rev", "question": "You are bargaining with a street vendor for a handicraft. What is the line between fair bargaining and exploitation?", "answer": "Reaching a price that is fair to both you and the artisan's labor", "options": ["Getting the lowest possible price, no matter what", "Paying the first price they ask without question", "Reaching a price that is fair to both you and the artisan's labor", "Walking away if they don't accept your first offer"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Fairness", "implication": "While bargaining is common, Dharma dictates that one should not deprive a worker of their fair due for their labor."}},
        {"id": "cult_i_8_rev", "question": "You wish to take a photograph of an elaborate religious ritual. What is the most respectful action?", "answer": "Ask for permission from the priest or participants before taking any photos", "options": ["Use a flash to get the best picture", "Take photos discreetly from a distance", "Ask for permission from the priest or participants before taking any photos", "Assume it is okay since it is in a public place"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Third Eye", "ethical_category": "Respect", "analysis": {"principle": "Respect for Sanctity", "implication": "A ritual is a sacred act, not a performance. Seeking permission shows you respect its spiritual significance."}},
        {"id": "cult_i_9_rev", "question": "A friend is observing a religious fast (like for Navratri or Ramzan). What is the most considerate thing to do?", "answer": "Avoid eating or drinking in front of them if possible", "options": ["Try to convince them to eat, citing health reasons", "Avoid eating or drinking in front of them if possible", "Ask them detailed questions about their fast", "Ignore it and eat as you normally would"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Empathy", "implication": "Showing consideration for their discipline demonstrates support and understanding for their spiritual practice."}},
        {"id": "cult_i_10_rev", "question": "A family member has passed away. For the mourning period, what is a traditional practice many families observe?", "answer": "Avoiding festive celebrations and wearing simple, subdued colors", "options": ["Hosting a large, celebratory party", "Going on a luxury vacation", "Avoiding festive celebrations and wearing simple, subdued colors", "Buying new, bright clothes"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Discipline", "analysis": {"principle": "Sobriety in Grief", "implication": "This period of austerity is a mark of respect for the departed soul and allows for quiet introspection and mourning."}},
        # Advanced (10) - Revised
        {"id": "cult_a_1_rev", "question": "A junior colleague touches your feet as a sign of respect. In a modern corporate environment, what is the most appropriate response?", "answer": "Gracefully accept the gesture, then later politely suggest it's not necessary in the workplace", "options": ["Scold them for being unprofessional", "Gracefully accept the gesture, then later politely suggest it's not necessary in the workplace", "Insist they do it every day", "Pretend it didn't happen"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Adapting Tradition", "implication": "This response respects their good intention while guiding them on modern professional etiquette."}},
        {"id": "cult_a_2_rev", "question": "You must refuse a wedding invitation from a very close senior relative. What is the best way to handle this?", "answer": "Call them personally to explain your reasons and send a gift anyway", "options": ["Simply do not show up", "Send a decline via a text message", "Call them personally to explain your reasons and send a gift anyway", "Ask a mutual relative to pass on the message"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Throat", "ethical_category": "Respect", "analysis": {"principle": "Maintaining Relationships", "implication": "A personal call shows that you value the relationship, and the gift honors the occasion even in your absence."}},
        {"id": "cult_a_3_rev", "question": "You are asked to be a tie-breaker in a property dispute between two relatives. According to Dharma, what is the wisest first step?", "answer": "Encourage them to seek a neutral, third-party mediator instead of making the decision yourself", "options": ["Side with the elder relative automatically", "Divide the property exactly in half, regardless of context", "Encourage them to seek a neutral, third-party mediator instead of making the decision yourself", "Refuse to get involved at all"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Justice", "analysis": {"principle": "Impartiality", "implication": "Placing yourself as the judge can permanently damage relationships. Promoting a fair, impartial process is the higher dharmic path."}},
        {"id": "cult_a_4_rev", "question": "A politician is openly using caste-based divisions to appeal for votes. For a dharmic citizen, this is a violation of what principle?", "answer": "The principle that all beings are manifestations of the same divine reality", "options": ["The principle of showing respect to leaders", "The principle that all beings are manifestations of the same divine reality", "The principle of following tradition", "The rules of political debate"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Unity", "analysis": {"principle": "Universal Oneness", "implication": "Dharma promotes unity and seeing the divine in all. Dividing society for personal gain is Adharma."}},
        {"id": "cult_a_5_rev", "question": "You see someone throwing offerings wrapped in plastic into a sacred river. What is the most constructive response?", "answer": "Politely approach them, acknowledge their devotion, and explain the harm plastic causes to the sacred river", "options": ["Take a picture and post it on social media to shame them", "Loudly confront them and call them a polluter", "Politely approach them, acknowledge their devotion, and explain the harm plastic causes to the sacred river", "Do nothing, as their intention is religious"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Throat", "ethical_category": "Duty", "analysis": {"principle": "Dharma towards Nature", "implication": "This approach respects their devotion while fulfilling one's duty to protect the environment (Prakriti)."}},
        {"id": "cult_a_6_rev", "question": "A family member wants to spend an excessive amount of money on a ritual to solve a problem. What is the wisest counsel?", "answer": "Advise that devotion (Bhakti) and right action (Karma) are more important than the scale of the ritual", "options": ["Encourage them, as bigger rituals bring better results", "Advise that devotion (Bhakti) and right action (Karma) are more important than the scale of the ritual", "Tell them all rituals are a waste of money", "Lend them the money to do it"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Essence over Form", "implication": "True Dharma emphasizes internal states and correct actions over external displays of wealth in rituals."}},
        {"id": "cult_a_7_rev", "question": "You must choose between a very high-paying job that harms the environment and a modest one that is eco-friendly. From a dharmic perspective, which is better?", "answer": "The modest, eco-friendly job, as it aligns with Ahimsa (non-harm)", "options": ["The high-paying job, as Artha (wealth) is a goal of life", "The modest, eco-friendly job, as it aligns with Ahimsa (non-harm)", "Neither, one should renounce work", "The high-paying job, as one can donate to environmental causes"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Ahimsa towards Nature", "implication": "The duty of non-harm extends to all of creation, including Mother Earth. Earning wealth through harmful means creates negative karma."}},
        {"id": "cult_a_8_rev", "question": "An ancient family tradition seems to contradict modern, ethical values (e.g., is discriminatory). What is the appropriate dharmic response?", "answer": "Respect the tradition's origins but adapt it to align with the higher principles of equality and compassion", "options": ["Follow the tradition blindly without question", "Completely reject all tradition as outdated", "Respect the tradition's origins but adapt it to align with the higher principles of equality and compassion", "Publicly ridicule the tradition"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Wisdom", "analysis": {"principle": "Yuga Dharma", "implication": "Dharma is not static. It must be interpreted with wisdom (Viveka) to fit the context of the present age, while upholding its eternal values."}},
        {"id": "cult_a_9_rev", "question": "You see a revered holy man acting in a clearly unethical manner. What does Dharma require of you?", "answer": "To trust your own conscience and moral principles, rather than blindly following a person", "options": ["To ignore it, as holy men are beyond judgment", "To trust your own conscience and moral principles, rather than blindly following a person", "To publicly expose them immediately", "To defend their actions no matter what"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Justice", "analysis": {"principle": "Viveka (Discrimination)", "implication": "Dharma is not about blind faith in individuals, but adherence to righteous principles. One's own conscience is the ultimate guide."}},
        {"id": "cult_a_10_rev", "question": "A friend insists that their interpretation of a scripture is the only correct one. How does the principle of 'Anekantavada' (from Jainism, but influential in Indian thought) guide a response?", "answer": "Acknowledge their perspective as one valid viewpoint, while suggesting that truth can be multifaceted", "options": ["Argue forcefully for your own interpretation", "Agree with them to avoid conflict", "Acknowledge their perspective as one valid viewpoint, while suggesting that truth can be multifaceted", "End the friendship over the disagreement"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Throat", "ethical_category": "Balance", "analysis": {"principle": "Many-Sidedness", "implication": "This principle promotes intellectual humility and acknowledges that complex truths can be viewed from multiple perspectives."}},
    ],
    "dharmic_principles": [
        {"id": "dharma_b_1", "question": "What is the principle of 'Ahimsa'?", "answer": "Non-harm or non-violence to all living beings", "options": ["Truthfulness", "Non-harm or non-violence to all living beings", "Generosity", "Purity"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Compassion", "implication": "It is the highest dharma and the foundation of ethical conduct."}},
        {"id": "dharma_b_2", "question": "The concept of 'Dharma' refers to one's...", "answer": "Duty, righteousness, and moral law", "options": ["Wealth", "Pleasure", "Duty, righteousness, and moral law", "Destiny"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Duty", "analysis": {"principle": "Moral Order", "implication": "Living according to Dharma upholds both personal and cosmic balance."}},
        {"id": "dharma_b_3", "question": "What is 'Satya'?", "answer": "The principle of truthfulness in thought, word, and deed", "options": ["The principle of truthfulness in thought, word, and deed", "The principle of non-stealing", "The principle of contentment", "The principle of cleanliness"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Throat", "ethical_category": "Honesty", "analysis": {"principle": "Integrity", "implication": "Truth is considered a fundamental aspect of the ultimate reality."}},
        {"id": "dharma_b_4", "question": "The law of 'Karma' means that...", "answer": "Every action has a corresponding reaction or consequence", "options": ["Everything is predetermined", "Every action has a corresponding reaction or consequence", "Some people are born lucky", "The gods control everything"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Cause and Effect", "analysis": {"principle": "Action and Reaction", "implication": "One is responsible for their own destiny, which is shaped by their actions."}},
        {"id": "dharma_b_5", "question": "What does 'Seva' mean?", "answer": "Selfless service without expectation of reward", "options": ["Pilgrimage", "Fasting", "Selfless service without expectation of reward", "Worship"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Selflessness", "implication": "It is a practical way to practice Karma Yoga and purify the self."}},
        {"id": "dharma_b_6", "question": "The principle of 'Daya' means having what for all beings?", "answer": "Compassion", "options": ["Respect", "Compassion", "Authority", "Patience"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Empathy", "implication": "Daya is the active form of sympathy, motivating one to alleviate the suffering of others."}},
        {"id": "dharma_b_7", "question": "'Santosha' is the principle of...", "answer": "Contentment", "options": ["Discipline", "Faith", "Contentment", "Courage"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Balance", "analysis": {"principle": "Inner Peace", "implication": "Contentment with what one has is a key to happiness and spiritual progress."}},
        {"id": "dharma_b_8", "question": "What is 'Puja'?", "answer": "A form of worship or devotional service to a deity", "options": ["A type of food", "A form of worship or devotional service to a deity", "A sacred place", "A philosophical debate"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Devotion", "analysis": {"principle": "Devotion", "implication": "Puja is a way to express reverence and connect with the divine."}},
        {"id": "dharma_b_9", "question": "'Atithi Devo Bhava' translates to what important principle?", "answer": "The guest is equivalent to God", "options": ["Truth alone triumphs", "The world is one family", "The guest is equivalent to God", "Knowledge is power"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Hospitality", "implication": "It teaches one to treat every guest with the utmost respect and honor."}},
        {"id": "dharma_b_10", "question": "What is 'Moksha'?", "answer": "Liberation from the cycle of birth and death", "options": ["Heaven", "Wealth", "Liberation from the cycle of birth and death", "Worldly success"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Crown", "ethical_category": "Purpose", "analysis": {"principle": "Ultimate Goal", "implication": "It is the final Purushartha, representing the attainment of ultimate freedom and self-realization."}},
        {"id": "dharma_i_1", "question": "What are the four 'Ashramas' or stages of life?", "answer": "Brahmacharya, Grihastha, Vanaprastha, Sannyasa", "options": ["Childhood, Adulthood, Middle Age, Old Age", "Student, Worker, Manager, Retiree", "Brahmacharya, Grihastha, Vanaprastha, Sannyasa", "Dharma, Artha, Kama, Moksha"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Duty", "analysis": {"principle": "Life's Journey", "implication": "This framework outlines the ideal progression of an individual's life, with evolving duties and goals."}},
        {"id": "dharma_i_2", "question": "The concept of 'Samsara' refers to what?", "answer": "The cycle of death and rebirth", "options": ["A religious scripture", "A temple", "The cycle of death and rebirth", "A pilgrimage site"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Cause and Effect", "analysis": {"principle": "The Worldly Cycle", "implication": "The ultimate spiritual goal (Moksha) is to be liberated from Samsara."}},
        {"id": "dharma_i_3", "question": "What is 'Svadharma'?", "answer": "One's own individual or personal duty", "options": ["The duty of kings", "Universal duty", "One's own individual or personal duty", "The duty of ascetics"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Duty", "analysis": {"principle": "Personal Path", "implication": "The Bhagavad Gita teaches that it is better to perform one's own dharma imperfectly than another's perfectly."}},
        {"id": "dharma_i_4", "question": "The principle of 'Brahmacharya' literally means 'walking with Brahman'. In practice, it often refers to what?", "answer": "Celibacy and control of the senses", "options": ["Studying the Vedas", "Living in a forest", "Celibacy and control of the senses", "Worshipping Brahma"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Sacral", "ethical_category": "Discipline", "analysis": {"principle": "Energy Conservation", "implication": "It is the practice of conserving vital energy to redirect it towards spiritual goals."}},
        {"id": "dharma_i_5", "question": "What does the phrase 'Vasudhaiva Kutumbakam' mean?", "answer": "The world is one family", "options": ["May all be happy", "The world is one family", "Truth alone triumphs", "I am Brahman"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Universalism", "implication": "This Mahaupanishad verse expresses a philosophy of universal brotherhood and global unity."}},
        {"id": "dharma_i_6", "question": "The principle of 'Tapas' refers to what?", "answer": "Austerity, self-discipline, and spiritual practice", "options": ["Charity", "Austerity, self-discipline, and spiritual practice", "Pilgrimage", "Chanting"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Discipline", "analysis": {"principle": "Spiritual Heat", "implication": "Tapas is the disciplined effort that purifies the individual and builds spiritual power."}},
        {"id": "dharma_i_7", "question": "How does 'Prarabdha Karma' differ from 'Sanchita Karma'?", "answer": "Prarabdha is the portion of past karma currently being experienced, while Sanchita is the total accumulation", "options": ["Prarabdha is good karma, Sanchita is bad karma", "Prarabdha is the portion of past karma currently being experienced, while Sanchita is the total accumulation", "They are the same", "Prarabdha is future karma, Sanchita is past karma"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Cause and Effect", "analysis": {"principle": "Types of Karma", "implication": "This explains why life's events unfold as they do, based on a subset of one's past actions."}},
        {"id": "dharma_i_8", "question": "'Ishvara Pranidhana' is a principle that involves what?", "answer": "Devotion and surrender to a higher power or God", "options": ["Self-study", "Cleanliness", "Devotion and surrender to a higher power or God", "Austerity"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Crown", "ethical_category": "Devotion", "analysis": {"principle": "Surrender", "implication": "It is the practice of offering one's actions and self to the divine, releasing the ego."}},
        {"id": "dharma_i_9", "question": "What is 'Viveka' in a spiritual context?", "answer": "The power of discrimination between the real and the unreal", "options": ["Memory", "Courage", "The power of discrimination between the real and the unreal", "Humility"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Discernment", "implication": "Viveka is considered the crucial first step on the path of knowledge (Jnana Yoga)."}},
        {"id": "dharma_i_10", "question": "The principle of 'Dana' (charity) is considered most pure when it is given...", "answer": "To a worthy recipient, without expectation of return, at a proper time and place", "options": ["Publicly to gain fame", "To a worthy recipient, without expectation of return, at a proper time and place", "Reluctantly", "To receive a favor in return"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Right Giving", "implication": "The quality and intention behind charity are more important than the amount given."}},
        {"id": "dharma_a_1", "question": "What is 'Vairagya'?", "answer": "Dispassion or detachment from worldly objects and desires", "options": ["Passion for life", "Dispassion or detachment from worldly objects and desires", "Social responsibility", "Ritual purity"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Discipline", "analysis": {"principle": "Renunciation", "implication": "Vairagya, combined with Viveka (discrimination), is essential for attaining Moksha."}},
        {"id": "dharma_a_2", "question": "'Sanatana Dharma' is often used to describe Hinduism. What is its literal meaning?", "answer": "The Eternal Law or Way", "options": ["The Indian Way", "The Way of the Gods", "The Eternal Law or Way", "The Ancient Religion"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Purpose", "analysis": {"principle": "Timelessness", "implication": "It suggests that its principles are universal and not limited to a specific time, place, or person."}},
        {"id": "dharma_a_3", "question": "What distinguishes 'Sakama Karma' from 'Nishkama Karma'?", "answer": "Sakama Karma is action performed with a selfish desire for results; Nishkama Karma is selfless action", "options": ["Sakama is good karma, Nishkama is bad", "Sakama Karma is action performed with a selfish desire for results; Nishkama Karma is selfless action", "Sakama is action in thought, Nishkama is physical action", "There is no difference"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Heart", "ethical_category": "Duty", "analysis": {"principle": "Motivation of Action", "implication": "The path of Karma Yoga emphasizes transforming Sakama Karma into Nishkama Karma."}},
        {"id": "dharma_a_4", "question": "The concept of 'Rta' in the Vedas refers to what?", "answer": "The cosmic order and principle of natural law", "options": ["A ritual sacrifice", "The cosmic order and principle of natural law", "A class of priests", "A specific deity"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Order", "analysis": {"principle": "Cosmic Law", "implication": "Rta is the precursor to the concept of Dharma, signifying the inherent order that governs the universe."}},
        {"id": "dharma_a_5", "question": "What is 'Manana' in the context of Jnana Yoga (the path of knowledge)?", "answer": "Deep reflection and contemplation on philosophical truths", "options": ["Listening to teachings", "Deep reflection and contemplation on philosophical truths", "Meditation", "Debating"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Intellectual Assimilation", "implication": "It is the second step after 'Shravana' (listening), where one logically processes and internalizes the teachings."}},
        {"id": "dharma_a_6", "question": "What is the principle of 'Samadarshana'?", "answer": "Seeing all beings with an equal eye, recognizing the divine in all", "options": ["Strict adherence to rules", "Seeing all beings with an equal eye, recognizing the divine in all", "Worshipping one's ancestors", "Social hierarchy"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Equal Vision", "implication": "A self-realized person sees the same Atman (self) in a scholar, a cow, an elephant, a dog, and an outcaste."}},
        {"id": "dharma_a_7", "question": "'Kriyaman Karma' is the karma that...", "answer": "Is being created in the present moment", "options": ["Has already fructified", "Is stored from past lives", "Is being created in the present moment", "Is a collective karma of a nation"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Cause and Effect", "analysis": {"principle": "Present Action", "implication": "This is the only type of karma over which we have immediate control through free will."}},
        {"id": "dharma_a_8", "question": "What is 'Shaucha'?", "answer": "Purity and cleanliness, both internal and external", "options": ["Austerity", "Contentment", "Purity and cleanliness, both internal and external", "Devotion"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Sacral", "ethical_category": "Purity", "analysis": {"principle": "Purity", "implication": "External purity involves hygiene, while internal purity relates to the cleanliness of thoughts and intentions."}},
        {"id": "dharma_a_9", "question": "The term 'Yuga Dharma' implies that...", "answer": "The specific expression of Dharma changes according to the prevailing age or epoch", "options": ["Dharma is the same in all ages", "Dharma is only for youth", "The specific expression of Dharma changes according to the prevailing age or epoch", "Dharma is a man-made concept"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Adaptive Righteousness", "implication": "While the core principles of Sanatana Dharma are eternal, their application can vary based on the context of the era."}},
        {"id": "dharma_a_10", "question": "What is the concept of 'Adhikara' in a spiritual context?", "answer": "The spiritual competency or qualification of a person for a certain practice or knowledge", "options": ["Divine authority", "The spiritual competency or qualification of a person for a certain practice or knowledge", "A type of scripture", "A hereditary title"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Spiritual Aptitude", "implication": "It suggests that spiritual teachings and practices should be appropriate to the student's level of development."}},
    ],
    "history": [
        # Basic (10) - Revised
        {"id": "hist_b_1_rev", "question": "The famous ancient city of Mohenjo-daro is a key site of which civilization?", "answer": "Indus Valley Civilization", "options": ["Vedic Civilization", "Maurya Civilization", "Indus Valley Civilization", "Gupta Civilization"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Legacy", "analysis": {"principle": "Ancient Origins", "implication": "The advanced urban planning of this civilization shows a sophisticated society in ancient India."}},
        {"id": "hist_b_2_rev", "question": "Who was the first Prime Minister of independent India?", "answer": "Jawaharlal Nehru", "options": ["Sardar Patel", "Mahatma Gandhi", "Jawaharlal Nehru", "B. R. Ambedkar"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Throat", "ethical_category": "Leadership", "analysis": {"principle": "Nation Building", "implication": "Nehru's leadership shaped India's early policies on democracy, socialism, and non-alignment."}},
        {"id": "hist_b_3_rev", "question": "The Taj Mahal was built by which Mughal emperor in memory of his wife?", "answer": "Shah Jahan", "options": ["Akbar", "Aurangzeb", "Shah Jahan", "Babur"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Devotion", "analysis": {"principle": "Monument of Love", "implication": "It stands as a timeless symbol of love and architectural genius."}},
        {"id": "hist_b_4_rev", "question": "Mahatma Gandhi led the famous 'Dandi March' or 'Salt March' to protest what?", "answer": "The British tax on salt", "options": ["High price of cloth", "The British tax on salt", "The partition of Bengal", "Forced indigo cultivation"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Justice", "analysis": {"principle": "Civil Disobedience", "implication": "This act of non-violent protest was a pivotal moment in India's struggle for independence."}},
        {"id": "hist_b_5_rev", "question": "The emperor Ashoka the Great belonged to which dynasty?", "answer": "Mauryan Dynasty", "options": ["Gupta Dynasty", "Chola Dynasty", "Mauryan Dynasty", "Kushan Dynasty"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Heart", "ethical_category": "Compassion", "analysis": {"principle": "Transformation", "implication": "Ashoka's conversion to Buddhism after the Kalinga war transformed him from a conqueror to a propagator of Dharma."}},
        {"id": "hist_b_6_rev", "question": "Who is known as the 'Iron Man of India' for his role in integrating the princely states?", "answer": "Sardar Vallabhbhai Patel", "options": ["Jawaharlal Nehru", "Sardar Vallabhbhai Patel", "Subhas Chandra Bose", "Lal Bahadur Shastri"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Unity", "analysis": {"principle": "Unification", "implication": "His determination was crucial in creating the political map of modern India."}},
        {"id": "hist_b_7_rev", "question": "The 'Quit India' Movement, a major call for British withdrawal, was launched in which year?", "answer": "1942", "options": ["1920", "1930", "1942", "1947"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Solar Plexus", "ethical_category": "Justice", "analysis": {"principle": "Call for Freedom", "implication": "This was the final mass movement led by Gandhi, significantly weakening British control."}},
        {"id": "hist_b_8_rev", "question": "Who founded the Mughal Empire in India?", "answer": "Babur", "options": ["Akbar", "Humayun", "Babur", "Shah Jahan"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Legacy", "analysis": {"principle": "New Beginnings", "implication": "Babur's victory at the Battle of Panipat laid the foundation for centuries of Mughal rule."}},
        {"id": "hist_b_9_rev", "question": "The Indian National Anthem, 'Jana Gana Mana', was composed by whom?", "answer": "Rabindranath Tagore", "options": ["Bankim Chandra Chatterjee", "Rabindranath Tagore", "Sarojini Naidu", "Swami Vivekananda"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Throat", "ethical_category": "Unity", "analysis": {"principle": "Ode to the Nation", "implication": "The anthem is a prayer for the well-being and unity of the diverse land of India."}},
        {"id": "hist_b_10_rev", "question": "The Battle of Plassey in 1757 is significant because it marked the beginning of...", "answer": "British East India Company rule in India", "options": ["Mughal rule", "The Delhi Sultanate", "British East India Company rule in India", "French colonial rule"], "type": "multiple_choice", "difficulty": "basic", "chakra": "Root", "ethical_category": "Conflict", "analysis": {"principle": "Shift in Power", "implication": "This battle was a decisive victory that paved the way for British colonization of the subcontinent."}},
        # Intermediate (10) - Revised
        {"id": "hist_i_1_rev", "question": "The 'Golden Age of India', known for great achievements in science, art, and literature, refers to the period of which empire?", "answer": "The Gupta Empire", "options": ["The Maurya Empire", "The Chola Empire", "The Gupta Empire", "The Mughal Empire"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Third Eye", "ethical_category": "Legacy", "analysis": {"principle": "Flourishing of Knowledge", "implication": "This era saw advancements like the concept of zero and the works of Kalidasa."}},
        {"id": "hist_i_2_rev", "question": "Who founded the Mauryan Empire with the help of his advisor Chanakya?", "answer": "Chandragupta Maurya", "options": ["Ashoka", "Bindusara", "Chandragupta Maurya", "Samudragupta"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Leadership", "analysis": {"principle": "Strategic Alliance", "implication": "The combination of Chanakya's intellect and Chandragupta's military skill created one of India's largest empires."}},
        {"id": "hist_i_3_rev", "question": "The Jallianwala Bagh massacre, where British troops fired on a peaceful gathering, took place in 1919 in which city?", "answer": "Amritsar", "options": ["Delhi", "Lahore", "Amritsar", "Kolkata"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Conflict", "analysis": {"principle": "Brutality and Resistance", "implication": "This tragic event was a turning point, galvanizing the Indian independence movement."}},
        {"id": "hist_i_4_rev", "question": "The first major Indian War of Independence against the British East India Company took place in which year?", "answer": "1857", "options": ["1757", "1857", "1919", "1942"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Conflict", "analysis": {"principle": "The Great Uprising", "implication": "Though unsuccessful, it marked the end of Company rule and the start of direct British Crown rule."}},
        {"id": "hist_i_5_rev", "question": "Chanakya, the advisor to Chandragupta Maurya, wrote which famous treatise on statecraft and political science?", "answer": "Arthashastra", "options": ["Vedas", "Ramayana", "Arthashastra", "Panchatantra"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Third Eye", "ethical_category": "Wisdom", "analysis": {"principle": "Political Realism", "implication": "The Arthashastra is a practical guide to governance, economics, and military strategy."}},
        {"id": "hist_i_6_rev", "question": "Who was the great Maratha warrior king who successfully challenged the Mughal Empire in the 17th century?", "answer": "Shivaji Maharaj", "options": ["Peshwa Bajirao", "Sambhaji", "Shivaji Maharaj", "Rana Pratap"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Solar Plexus", "ethical_category": "Leadership", "analysis": {"principle": "Guerilla Warfare", "implication": "Shivaji is celebrated for his administrative skills, military strategies, and for establishing a sovereign Maratha nation."}},
        {"id": "hist_i_7_rev", "question": "The 'Doctrine of Lapse' was a policy of annexation used by the British, formulated by which Governor-General?", "answer": "Lord Dalhousie", "options": ["Lord Curzon", "Lord Wellesley", "Lord Dalhousie", "Lord Canning"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Root", "ethical_category": "Conflict", "analysis": {"principle": "Annexation Policy", "implication": "This unjust policy was one of the major political causes of the 1857 revolt."}},
        {"id": "hist_i_8_rev", "question": "The Mughal emperor Akbar was known for promoting a syncretic religion known as...", "answer": "Din-i-Ilahi", "options": ["Sufism", "Din-i-Ilahi", "Bhakti", "Islam"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Heart", "ethical_category": "Unity", "analysis": {"principle": "Religious Tolerance", "implication": "Akbar's attempt to merge the best elements of different religions was a testament to his policy of inclusion."}},
        {"id": "hist_i_9_rev", "question": "Who was the first woman to rule the Delhi Sultanate?", "answer": "Razia Sultana", "options": ["Chand Bibi", "Nur Jahan", "Razia Sultana", "Mumtaz Mahal"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Throat", "ethical_category": "Leadership", "analysis": {"principle": "Breaking Barriers", "implication": "Razia Sultana's reign in the 13th century was a remarkable, though short-lived, challenge to patriarchal norms."}},
        {"id": "hist_i_10_rev", "question": "The European who first discovered the sea route to India in 1498 was...", "answer": "Vasco da Gama", "options": ["Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Marco Polo"], "type": "multiple_choice", "difficulty": "intermediate", "chakra": "Sacral", "ethical_category": "Legacy", "analysis": {"principle": "Global Connection", "implication": "His voyage opened up maritime trade between Europe and India, leading to profound global changes."}},
        # Advanced (10) - Revised
        {"id": "hist_a_1_rev", "question": "The 'Drain of Wealth' theory, which argued that British policies were depleting India's resources, was formulated by whom?", "answer": "Dadabhai Naoroji", "options": ["R. C. Dutt", "Dadabhai Naoroji", "Gopal Krishna Gokhale", "M. G. Ranade"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Third Eye", "ethical_category": "Justice", "analysis": {"principle": "Economic Critique", "implication": "This theory was crucial in establishing an economic basis for the Indian nationalist movement."}},
        {"id": "hist_a_2_rev", "question": "The 'Poona Pact' of 1932 was an agreement between Mahatma Gandhi and which other leader regarding electoral seats for depressed classes?", "answer": "B. R. Ambedkar", "options": ["Jawaharlal Nehru", "Sardar Patel", "B. R. Ambedkar", "Muhammad Ali Jinnah"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Throat", "ethical_category": "Justice", "analysis": {"principle": "Political Compromise", "implication": "This pact was a major event concerning political representation for the Dalit community."}},
        {"id": "hist_a_3_rev", "question": "The slogan 'Swaraj is my birthright and I shall have it!' is attributed to which nationalist leader?", "answer": "Bal Gangadhar Tilak", "options": ["Mahatma Gandhi", "Subhas Chandra Bose", "Bal Gangadhar Tilak", "Lala Lajpat Rai"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Solar Plexus", "ethical_category": "Justice", "analysis": {"principle": "Radical Nationalism", "implication": "Tilak's assertive declaration marked a shift towards a more aggressive form of nationalism."}},
        {"id": "hist_a_4_rev", "question": "The Battle of Talikota in 1565 led to the catastrophic defeat and decline of which powerful South Indian empire?", "answer": "The Vijayanagara Empire", "options": ["The Chola Empire", "The Pandya Empire", "The Vijayanagara Empire", "The Satavahana Empire"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Root", "ethical_category": "Conflict", "analysis": {"principle": "End of an Era", "implication": "This battle effectively ended the last great Hindu empire in South India."}},
        {"id": "hist_a_5_rev", "question": "Who was the last Governor-General of British India and the first Governor-General of independent India?", "answer": "Lord Mountbatten", "options": ["Lord Curzon", "C. Rajagopalachari", "Lord Mountbatten", "Lord Wavell"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Leadership", "analysis": {"principle": "Transition of Power", "implication": "Mountbatten oversaw the partition and independence of India and Pakistan."}},
        {"id": "hist_a_6_rev", "question": "The 'Permanent Settlement' of Bengal, a land revenue system with far-reaching consequences, was introduced by whom?", "answer": "Lord Cornwallis", "options": ["Warren Hastings", "Lord Cornwallis", "Lord Wellesley", "Robert Clive"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Root", "ethical_category": "Legacy", "analysis": {"principle": "Land Tenure System", "implication": "It created a new class of landlords (Zamindars) and had a profound impact on the agrarian structure of Eastern India."}},
        {"id": "hist_a_7_rev", "question": "The 'Ryotwari System' of land revenue collection was primarily introduced in which part of India?", "answer": "South India", "options": ["Bengal", "Punjab", "South India", "Central Provinces"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Root", "ethical_category": "Legacy", "analysis": {"principle": "Direct Taxation", "implication": "Under this system, the government collected taxes directly from the peasant cultivators (ryots)."}},
        {"id": "hist_a_8_rev", "question": "The resolution for 'Purna Swaraj' or complete independence was passed by the Indian National Congress at which session?", "answer": "The Lahore Session of 1929", "options": ["The Surat Session of 1907", "The Lucknow Session of 1916", "The Lahore Session of 1929", "The Karachi Session of 1931"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Throat", "ethical_category": "Justice", "analysis": {"principle": "Declaration of Independence", "implication": "This was a momentous step, shifting the goal from dominion status to complete freedom."}},
        {"id": "hist_a_9_rev", "question": "Who was the president of the Indian National Congress at the time of India's independence in August 1947?", "answer": "J. B. Kripalani", "options": ["Jawaharlal Nehru", "Mahatma Gandhi", "J. B. Kripalani", "Sardar Patel"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Crown", "ethical_category": "Leadership", "analysis": {"principle": "Transitional Leadership", "implication": "Kripalani presided over the Congress during the critical period of the transfer of power."}},
        {"id": "hist_a_10_rev", "question": "The Simon Commission was boycotted by Indians because...", "answer": "It had no Indian members", "options": ["It proposed to divide India", "It had no Indian members", "It was against independence", "It recommended higher taxes"], "type": "multiple_choice", "difficulty": "advanced", "chakra": "Throat", "ethical_category": "Justice", "analysis": {"principle": "Self-Determination", "implication": "The all-white composition of the commission was seen as an insult and a denial of India's right to decide its own future."}},
    ]
}

def find_puzzle_by_id(puzzle_id):
    """
    Finds a puzzle by its ID and also returns its category name.
    Returns: A tuple (puzzle_dict, category_name) or (None, None) if not found.
    """
    for category_name, puzzles_in_category in PUZZLES.items():
        for puzzle in puzzles_in_category:
            if puzzle['id'] == puzzle_id:
                return (puzzle, category_name)
    return (None, None)

def generate_quiz_set(difficulty):
    """
    Generates a quiz set of 25 random questions for the specified
    difficulty level, ensuring no repetition in a single round.
    """
    all_puzzles_of_difficulty = []
    for category_name in PUZZLES:
        for puzzle in PUZZLES[category_name]:
            if puzzle.get('difficulty') == difficulty:
                all_puzzles_of_difficulty.append(puzzle)
    
    num_questions_to_ask = 25
    if len(all_puzzles_of_difficulty) < num_questions_to_ask:
        num_questions_to_ask = len(all_puzzles_of_difficulty)

    quiz_set = random.sample(all_puzzles_of_difficulty, num_questions_to_ask)
    return quiz_set

def get_karma_personality(score, total_questions=25):
    """
    Determines a user's karma personality based on their final score.
    """
    max_score = total_questions * 10
    score_percentage = (score / max_score) * 100 if max_score > 0 else 0

    if score_percentage >= 80:
        return "Enlightened Soul"
    elif score_percentage >= 40:
        return "Balanced Practitioner"
    elif score_percentage >= 0:
        return "Neutral Wanderer"
    else:
        return "Chaotic Spirit"

